[package]
name = "srsglass"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
chrono-tz = "0.9.0"
clap = { version = "4.5.15", features = ["derive"] }
flate2 = "1.0.31"
quick-xml = "0.36.1"
rust_xlsxwriter = "0.73.0"
ureq = "2.10.1"
