[package]
name = "srsglass"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
chrono-tz = "0.8.5"
clap = { version = "4.4.4", features = ["derive"] }
flate2 = "1.0.27"
quick-xml = "0.30.0"
rust_xlsxwriter = "0.49.0"
ureq = "2.7.1"
